version: '2'
services:
  server:
    environment:
      - 'NODE_ENV=production'
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'PORT=3000'
    image: 'arnheidur/tictactoe:${GIT_COMMIT}'
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres' # postgres needs to be up and running
    links:
      - 'postgres' # connect server to postgres
  postgres:        # database
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    image: 'postgres'
    ports:
      - '5432:5432'
