version: '2'
services:
  server:
    environment:
      - 'NODE_ENV=production'      # added to run in production environment
      - 'POSTGRES_HOST=postgres'   # for postgres and app running together
      - 'POSTGRES_PORT=5432'
      - 'PORT=3000'
    image: 'arnheidur13/tictactoe:${GIT_COMMIT}'    
    ports:
      - '80:3000'
    depends_on:
      - 'postgres' # postgres needs to be up and running
    links:
      - 'postgres' # links server to postgres
  postgres:        # database
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    image: 'postgres'
    ports:
      - '5432:5432'
