version: '2'
services:
  server:
    environment:
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
    image: 'arnheidur/tictactoe'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - 'postgres' # postgres needs to be up and running
    links:
      - 'postgres' # connect server to postgres
  postgres:        # database
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    image: 'postgres'
    ports:
      - '5432:5432'
